### ISSUE TITLE
support from RF devices such as broadlink

### ISSUE THREAD

**Issue by ohadlevy** [Nickduino/Pi-Somfy#14]
Hi,

Do you happen to know if its easy to use a tool such as broadlink rf (or any other generic rf device that is not installed directly on a pi?)
thanks

**Comment by Nickduino** [comment]
I've never seen one so take my answer with a pinch of salt.

If they can transmit on 433.42 MHz: maybe. In which case I'd advise you to check if:
- it isn't already possible to control the blinds;
- you can send  it any frame you which to be broadcasted (but I'm not convinced it's worth finding out since my solution costs 2€ in parts and works).

If they're only 433.92 MHz: no chance.

**Comment by ohadlevy** [comment]
thanks, can you perhaps provide a couple of example links/search terms to
the hw one need to buy?

**Comment by Nickduino** [comment]
Check the closed issues: https://github.com/Nickduino/Pi-Somfy/issues?utf8=%E2%9C%93&q=is%3Aissue

Any cheap chinese emitter with the right crystal should work.
