### ISSUE TITLE
Improving the GUI

### ISSUE THREAD

**Issue by Nickduino** [Nickduino/Pi-Somfy#21]
I've made a 3D render of a streamlined remote:
![image](https://user-images.githubusercontent.com/9784237/51989402-45c22300-24a7-11e9-9b40-27f4a32ab967.png)

The objective is to replace this:
![image](https://user-images.githubusercontent.com/9784237/51989551-9a659e00-24a7-11e9-8962-bf2872b6016f.png)

Any one has some knowledge of web designing and wants to help?
Possibly responsive design as well but not necessarily

**Comment by c6opuc** [comment]
First of all thank you guys for the great project and the level of maturity of the code and documentation! I managed to build the system that controls 7 blinds in just two days. The longest time took soldering for me and I could only overcome it by involving my friend :-) Otherwise it was extremely easy process and all worked from the first attempt! 
Is there any chance to revert the interface of operating the remotes to the old one? The new one is really not ready. There is overlapping of remote in Chrome on PC (see screenshot), and it is completely unusable on Android smartphone.

![image](https://user-images.githubusercontent.com/5767539/56386843-1e1b6500-6223-11e9-88e8-b017aa187beb.png)

**Comment by Nickduino** [comment]
Do you feel able to work on it?

If you want to revert back to the old way, have you tried the V2 ?
https://github.com/Nickduino/Pi-Somfy/releases

**Comment by c6opuc** [comment]
If I revert to V2 I will loose all other fixes regarding alexa, etc, right? 
I am not a web-dev and already had a look at the code. It is too complicated for me :-)

**Comment by Nickduino** [comment]
Well, Alexa should work with the last release.

For the rest, I know it's frustrating
