### ISSUE TITLE
erro launch operateshutters.conf

### ISSUE THREAD

**Issue by akuaman** [Nickduino/Pi-Somfy#96]
when lauch operateshutthers.py i have this error

This program requires the modules located from the same github repository that a                                                                                        re not present.

Error: No module named 'requests'

**Comment by KrejtSparck** [comment]
I triggered this exact same error om Python 2(!) (not on Python 3) and managed to solve the problem with the command "sudo pip install requests", after which a "sudo python /home/pi/Pi-Somfy/operateShutters.py" worked just fine. Strange that this went wrong on Python 2 at first, because nowhere the dependency on 'requests' is indicated (not in the requirements.txt or the README.md) and I don't see it used in the operateShutters.py code? I'm sure somebody (Nick?) can explain this....

**Comment by Nickduino** [comment]
Well, Nick would advise to use Python 3 😬
